# Makefile for main src

all:
	$(MAKE) -C julia/
#	$(MAKE) -C mandelbrot/

clean:
	$(MAKE) -C julia/ clean
#	$(MAKE) -C mandelbrot/ clean

cleaner:
	$(MAKE) -C julia/ cleaner
#	$(MAKE) -C mandelbrot/ cleaner

